// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview This file contains the Genkit flow for suggesting fixes for failed tests using Gemini.
 *
 * - suggestTestFixes: A function that takes test results and suggests fixes using Gemini.
 * - SuggestTestFixesInput: The input type for the suggestTestFixes function.
 * - SuggestTestFixesOutput: The output type for the suggestTestFixes function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestTestFixesInputSchema = z.object({
  testResults: z.string().describe('The test results, including details of failed tests.'),
  codebase: z.string().describe('The codebase associated with the tests.'),
});
export type SuggestTestFixesInput = z.infer<typeof SuggestTestFixesInputSchema>;

const SuggestTestFixesOutputSchema = z.object({
  suggestedFixes: z.string().describe('The suggested fixes for the failed tests.'),
});
export type SuggestTestFixesOutput = z.infer<typeof SuggestTestFixesOutputSchema>;

export async function suggestTestFixes(input: SuggestTestFixesInput): Promise<SuggestTestFixesOutput> {
  return suggestTestFixesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestTestFixesPrompt',
  input: {schema: SuggestTestFixesInputSchema},
  output: {schema: SuggestTestFixesOutputSchema},
  prompt: `You are an AI assistant helping developers fix failed tests.

  Based on the provided test results and codebase, suggest fixes for the failed tests.

  Test Results:
  {{testResults}}

  Codebase:
  {{codebase}}

  Suggested Fixes:`,
});

const suggestTestFixesFlow = ai.defineFlow(
  {
    name: 'suggestTestFixesFlow',
    inputSchema: SuggestTestFixesInputSchema,
    outputSchema: SuggestTestFixesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
